### PR TITLE
Polish title to remove 'redundancy'

### PR DESCRIPTION
**Pull request by maurolepore**
This commit reduces the chance CRAN will reject the package because
the phrase "Tool to" is redundant.

> I’ve been flagged for a “redundant” title. I had: “A Toolkit
for the Construction of Modeling Packages” which was flagged since
“Toolkit for” seemed redundant. I changed it to “Construct Modeling
Packages” and was accepted.
--https://github.com/DavisVaughan/extrachecks

### CODE REVIEW

**Review by gonzalezeb — APPROVED** [review]
Agree

**Comment by gonzalezeb** [comment]
There is a conflict in this branch but i am not sure how to solve it..

**Comment by maurolepore** [comment]
I think I solved the merge conflict. I you see all checks here pass, then you're good to merge.

**Comment by maurolepore** [comment]
Oh, I see you had already approved -- so I'll go ahead and merge.

**Pull request merged**
